# Generated by Django 4.1.4 on 2022-12-11 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True, serialize=False,
                                           verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True,
                                                 db_index=True)),
                ('modified', models.DateTimeField(
                    blank=True, db_index=True, null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('patronymic', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'patronymic'],
            },
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True, serialize=False,
                                           verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True,
                                                 db_index=True)),
                ('modified', models.DateTimeField(
                    blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='MarketWage',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True, serialize=False,
                                           verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True,
                                                 db_index=True)),
                ('modified', models.DateTimeField(
                    blank=True, db_index=True, null=True)),
                ('position', models.CharField(choices=[
                    ('Lead', (
                        ('LEAD_DEVELOPER', 'Ведущий разработчик'),
                        ('LEAD_1S', 'Ведущий разработчик 1С'),
                        ('LEAD_SOFTWARE',
                            'Ведущий разработчик программного обеспечения'),
                    )),
                    ('Chief', 'Главный разработчик'),
                    ('Junior', (
                        ('JUNIOR_PROGRAMMER', 'Младший программист'),
                        ('JUNIOR_DEVELOPER', 'Младший разработчик'),
                        ('JUNIOR_SOFTWARE_DEVELOPER',
                         'Младший разработчик программного обеспечения'),
                    )),
                    ('Junior specialist', (
                        ('JUNIOR_DEV_SPECIALIST',
                            'Младший специалист по разработке'),
                        ('JUNIOR_QA_SPECIALIST',
                         'Младший специалист по обеспечению качества'),
                    )),
                    ('Developer', (
                        ('DEVELOPER_COMMON', 'Разработчик'),
                        ('SOFTWARE_DEVELOPER',
                            'Разработчик программного обеспечения'),
                        ('QA_SPECIALIST',
                            'Специалист по обеспечению качества'),
                    )),
                    ('Team Leader', (
                        ('DEVELOPMENT_TEAM_LEADER',
                            'Руководитель группы разработки'),
                        ('SOFTWARE_DEVELOPMENT_TEAM_LEADER',
                         'Руководитель группы разработки ПО'),
                    )),
                    ('DEPARTMENT_HEAD', 'Руководитель отдела'),
                    ('Senior', (
                        ('SENIOR_DEVELOPER', 'Старший разработчик'),
                        ('SENIOR_SOFTWARE_DEVELOPER',
                            'Старший разработчик ПО'),
                        ('SENIOR_SOFTWARE_DEVELOPER_FULL',
                         'Старший разработчик программного обеспечения'),
                    )),
                    ('EXPERT', 'Эксперт разработчик'),
                ], max_length=50)),
                ('wage', models.FloatField()),
                ('comment', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True, serialize=False,
                                           verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True,
                                                 db_index=True)),
                ('modified', models.DateTimeField(
                    blank=True, db_index=True, null=True)),
                ('minimum', models.FloatField()),
                ('comfort', models.FloatField()),
                ('employee', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    to='fot.employee')),
            ],
            options={
                'verbose_name_plural': 'Wishes',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Wage',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True, serialize=False,
                                           verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True,
                                                 db_index=True)),
                ('modified', models.DateTimeField(
                    blank=True, db_index=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('salary', models.FloatField()),
                ('monthly_premium', models.FloatField(blank=True, null=True)),
                ('quarterly_premium', models.FloatField(blank=True,
                                                        null=True)),
                ('position', models.CharField(choices=[
                    ('Lead', (
                        ('LEAD_DEVELOPER', 'Ведущий разработчик'),
                        ('LEAD_1S', 'Ведущий разработчик 1С'),
                        ('LEAD_SOFTWARE',
                            'Ведущий разработчик программного обеспечения'),
                    )),
                    ('Chief', 'Главный разработчик'),
                    ('Junior', (
                        ('JUNIOR_PROGRAMMER', 'Младший программист'),
                        ('JUNIOR_DEVELOPER', 'Младший разработчик'),
                        ('JUNIOR_SOFTWARE_DEVELOPER',
                         'Младший разработчик программного обеспечения'),
                    )),
                    ('Junior specialist', (
                        ('JUNIOR_DEV_SPECIALIST',
                            'Младший специалист по разработке'),
                        ('JUNIOR_QA_SPECIALIST',
                         'Младший специалист по обеспечению качества'),
                    )),
                    ('Developer', (
                        ('DEVELOPER_COMMON', 'Разработчик'),
                        ('SOFTWARE_DEVELOPER',
                            'Разработчик программного обеспечения'),
                        ('QA_SPECIALIST',
                            'Специалист по обеспечению качества'),
                    )),
                    ('Team Leader', (
                        ('DEVELOPMENT_TEAM_LEADER',
                            'Руководитель группы разработки'),
                        ('SOFTWARE_DEVELOPMENT_TEAM_LEADER',
                         'Руководитель группы разработки ПО'),
                    )),
                    ('DEPARTMENT_HEAD', 'Руководитель отдела'),
                    ('Senior', (
                        ('SENIOR_DEVELOPER', 'Старший разработчик'),
                        ('SENIOR_SOFTWARE_DEVELOPER',
                            'Старший разработчик ПО'),
                        ('SENIOR_SOFTWARE_DEVELOPER_FULL',
                         'Старший разработчик программного обеспечения'),
                    )),
                    ('EXPERT', 'Эксперт разработчик'),
                ], max_length=50)),
                ('employee', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    to='fot.employee')),
                ('forecast',
                    models.ForeignKey(
                        blank=True, null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to='fot.forecast')),
            ],
        ),
        migrations.AddConstraint(
            model_name='wage',
            constraint=models.UniqueConstraint(
                fields=('forecast', 'employee'),
                name='unique_forecast_employee_combination'),
        ),
    ]
