# Generated by Django 4.1.4 on 2022-12-11 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wage',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='wage',
            name='rate',
            field=models.FloatField(default=1),
        ),
    ]
