# Generated by Django 4.1.4 on 2022-12-12 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fot', '0002_wage_department_wage_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='wage',
            name='district_coefficient',
            field=models.FloatField(default=1),
        ),
    ]
