# Generated by Django 4.1.4 on 2022-12-14 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fot', '0004_alter_wage_options_alter_wage_monthly_premium_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wage',
            name='forecast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fot.forecast'),
        ),
    ]
