# Generated by Django 4.1.4 on 2022-12-21 05:42

from django.db import migrations, models


def fill_up_aprooved(apps, schema_editor):
    Wage = apps.get_model('fot', 'Wage')
    for wage in Wage.objects.all():
        wage.aprooved = wage.created
        wage.save()


class Migration(migrations.Migration):

    dependencies = [
        ('fot', '0005_cascade_delete_forecast'),
    ]

    operations = [
        migrations.AddField(
            model_name='wage',
            name='aprooved',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(fill_up_aprooved),
    ]
