# Generated by Django 4.1.4 on 2023-03-01 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fot', '0007_alter_wage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
